use_frameworks!

target 'CMAuthenticate_Example' do
  pod 'CMAuthenticate', :path => '../'

  target 'CMAuthenticate_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
